server:
  port: 8013

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: dharma-service

management:
  security:
    enabled: false

logging:
  level:
    com.dharma.springcloud.dharmamallservice: DEBUG